#include "kmain.h"
#include "kprintf.h"
#include "snprintf.h"
#include "string.h"
#include "vga/vga.h"
#include "splash.h"
#include "core/panic.h"
#include "version.h"
#include "sound/speaker.h"
#include "music/music.h"

// Auto-generated by midi_to_zuzu.py
// Source: un_owen.mid
// Tempo: 160 BPM
// Tracks available: 1 (using track 0)

// Auto-generated by midi_to_zuzu.py
// Source: boot.mid
// Tempo: 160 BPM
// Tracks available: 1 (using track 0)

void play_zuzu(void) {
    static const note_t notes[] = {
        {NOTE_C4, 4},
        {NOTE_DS4, 4},
        {NOTE_G3, 4},
        {NOTE_C4, 4},
        {NOTE_E4, 4},
        {NOTE_C4, 4},
        {NOTE_E4, 4},
        {NOTE_C5, 4},
        {NOTE_G4, 4},
        {NOTE_C5, 4},
        {NOTE_G4, 4},
        {NOTE_E4, 4},
        {NOTE_E5, 16},
    };

    static const song_t song = {
        .notes  = notes,
        .length = 13,
        .tempo  = 80,
    };

    play_melody(&song);
}

_Noreturn void kmain(void) {
    vga_clear();
    kprintf_init(vga_putc);
    splash();
    kprintf("Welcome to Zuzu386 (version %s)!\n", Z386_VERSION);
    play_zuzu();
    while (1);
}