#!/usr/bin/env python3
"""
midi_to_zuzu.py - Convert MIDI files to zuzu386 note_t arrays
Usage: python3 midi_to_zuzu.py <input.mid> [track_index] [function_name]

Requires: pip install mido
"""

import sys
import mido

NOTE_PREFIXES = [
    "NOTE_C", "NOTE_CS", "NOTE_D", "NOTE_DS", "NOTE_E", "NOTE_F",
    "NOTE_FS", "NOTE_G", "NOTE_GS", "NOTE_A", "NOTE_AS", "NOTE_B"
]

MIN_SUPPORTED_MIDI = 12   # C0
MAX_SUPPORTED_MIDI = 119  # B8

def ticks_to_beat_units(ticks, ticks_per_beat):
    """Convert MIDI ticks to zuzu386 beat units (8 = one beat)"""
    return max(1, round((ticks / ticks_per_beat) * 8))


def midi_note_to_enum(note_num):
    """Map MIDI note number to NOTE_* enum name defined in kernel/music/music.h."""
    clamped = min(max(note_num, MIN_SUPPORTED_MIDI), MAX_SUPPORTED_MIDI)
    octave = (clamped // 12) - 1
    prefix = NOTE_PREFIXES[clamped % 12]
    enum_name = f"{prefix}{octave}"
    was_clamped = clamped != note_num
    return enum_name, was_clamped


def extract_highest_voice(track, ticks_per_beat):
    """Extract a monophonic line by taking the highest active note at each time slice."""
    events = []
    current_tick = 0

    for msg in track:
        current_tick += msg.time
        if msg.type == 'note_on' and msg.velocity > 0:
            events.append((current_tick, msg.note, True))
        elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
            events.append((current_tick, msg.note, False))

    if not events:
        return []

    active_counts = {}
    segments = []
    segment_start = 0
    current_note = None
    idx = 0

    while idx < len(events):
        tick = events[idx][0]

        if tick > segment_start:
            segments.append((current_note, segment_start, tick))
            segment_start = tick

        # Apply all note changes at this tick before selecting the voice for the next slice.
        while idx < len(events) and events[idx][0] == tick:
            _, note_num, is_on = events[idx]
            if is_on:
                active_counts[note_num] = active_counts.get(note_num, 0) + 1
            else:
                count = active_counts.get(note_num, 0)
                if count <= 1:
                    active_counts.pop(note_num, None)
                else:
                    active_counts[note_num] = count - 1
            idx += 1

        current_note = max(active_counts) if active_counts else None

    notes = []
    for note_num, start_tick, end_tick in segments:
        duration_ticks = end_tick - start_tick
        if duration_ticks <= 0:
            continue

        duration_units = ticks_to_beat_units(duration_ticks, ticks_per_beat)
        if notes and notes[-1][0] == note_num:
            prev_note, prev_duration, _ = notes[-1]
            notes[-1] = (prev_note, prev_duration + duration_units, end_tick)
        else:
            notes.append((note_num, duration_units, end_tick))

    return notes

def midi_to_zuzu(midi_path, track_index=0, function_name=None):
    mid = mido.MidiFile(midi_path)
    ticks_per_beat = mid.ticks_per_beat

    # find tempo (microseconds per beat), default 500000 = 120 BPM
    tempo = 500000
    for track in mid.tracks:
        for msg in track:
            if msg.type == 'set_tempo':
                tempo = msg.tempo
                break

    bpm = round(60_000_000 / tempo)

    # pick track
    tracks_with_notes = [t for t in mid.tracks if any(m.type == 'note_on' for m in t)]
    if not tracks_with_notes:
        print("Error: no tracks with notes found")
        sys.exit(1)

    if track_index >= len(tracks_with_notes):
        print(f"Error: track {track_index} not found, {len(tracks_with_notes)} tracks available")
        sys.exit(1)

    track = tracks_with_notes[track_index]

    notes = extract_highest_voice(track, ticks_per_beat)

    if not notes:
        print("Error: no notes extracted")
        sys.exit(1)

    # generate function name from filename if not provided
    if function_name is None:
        import os
        base = os.path.splitext(os.path.basename(midi_path))[0]
        function_name = "play_" + base.lower().replace(" ", "_").replace("-", "_")

    # output
    print(f"// Auto-generated by midi_to_zuzu.py")
    print(f"// Source: {midi_path}")
    print(f"// Tempo: {bpm} BPM")
    print(f"// Tracks available: {len(tracks_with_notes)} (using track {track_index})")
    print()
    print(f"void {function_name}(void) {{")
    print(f"    static const note_t notes[] = {{")

    for note_num, duration, _ in notes:
        if note_num is None:
            print(f"        {{NOTE_REST, {duration}}},")
        else:
            name, clamped = midi_note_to_enum(note_num)
            if clamped:
                print(f"        {{{name}, {duration}}}, /* MIDI {note_num} clamped to C0-B8 */")
            else:
                print(f"        {{{name}, {duration}}},")

    print(f"    }};")
    print()
    print(f"    static const song_t song = {{")
    print(f"        .notes  = notes,")
    print(f"        .length = {len(notes)},")
    print(f"        .tempo  = {bpm},")
    print(f"    }};")
    print()
    print(f"    play_melody(&song);")
    print(f"}}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 midi_to_zuzu.py <input.mid> [track_index] [function_name]")
        print("  track_index:   which melody track to use (default 0)")
        print("  function_name: name for the generated C function (default: play_<filename>)")
        sys.exit(1)

    midi_path = sys.argv[1]
    track_index = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    function_name = sys.argv[3] if len(sys.argv) > 3 else None

    midi_to_zuzu(midi_path, track_index, function_name)